global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job", "camera_id"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "default-receiver"
  routes:
    - match:
        severity: critical
      receiver: "critical-receiver"

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: "http://gateway:8000/api/v1/notifications/alerts"
        send_resolved: true

  - name: "critical-receiver"
    webhook_configs:
      - url: "http://gateway:8000/api/v1/notifications/alerts"
        send_resolved: true
