apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mcpt-production

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: mcpt-gateway
    newName: registry.mcpt.com/production/gateway
  - name: mcpt-web
    newName: registry.mcpt.com/production/web
