import React from 'react';

export const testResultsStyles: Record<string, React.CSSProperties> = {
  container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
    padding: '16px 0',
  },
  successBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    backgroundColor: 'var(--color-success-bg)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    borderRadius: 'var(--radius-lg)',
    padding: '20px',
  },
  bannerText: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  bannerHeading: {
    fontSize: '16px',
    fontWeight: 600,
    color: 'var(--color-success)',
  },
  bannerSub: {
    fontSize: '13px',
    color: 'var(--color-text-secondary)',
    marginTop: '4px',
  },
  downloadBtn: {
    padding: '10px 20px',
    fontSize: '13px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: 'var(--color-text)',
    fontFamily: 'var(--font-heading)',
  },
  chartCard: {
    padding: '24px 16px 12px 16px',
  },
  cropsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
    gap: '16px',
  },
  cropCard: {
    backgroundColor: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: 'var(--radius-md)',
    overflow: 'hidden',
    boxShadow: 'var(--shadow-sm)',
    display: 'flex',
    flexDirection: 'column',
  },
  imageWrapper: {
    width: '100%',
    height: '130px',
    position: 'relative',
    backgroundColor: '#0c1017',
  },
  cropImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  classBadge: {
    position: 'absolute',
    bottom: '8px',
    left: '8px',
    fontSize: '10px',
    fontWeight: 700,
    color: 'white',
    padding: '4px 8px',
    borderRadius: 'var(--radius-sm)',
    fontFamily: 'var(--font-heading)',
  },
  cropMeta: {
    padding: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  cropTime: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    color: 'var(--color-text-secondary)',
  },
  cropConf: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    color: 'var(--color-text-secondary)',
  },
  emptyGallery: {
    gridColumn: '1 / -1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '40px',
    backgroundColor: 'var(--color-surface)',
    border: '1px dashed var(--color-border)',
    borderRadius: 'var(--radius-lg)',
  },
  emptyText: {
    fontSize: '13px',
    color: 'var(--color-text-secondary)',
  },
};
